services:
  prometheus:
    network_mode: host
    container_name: prometheus
    image: prom/prometheus:v2.47.0
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml --web.listen-address="0.0.0.0:9000" --web.enable-remote-write-receiver --enable-feature=native-histograms
  grafana:
    network_mode: host
    image: grafana/grafana:10.1.1
    container_name: grafana
    user: "0"
    volumes:
      - "./grafana/data:/var/lib/grafana"
      - "./grafana/provisioning:/etc/grafana/provisioning"
  otel-collector:
    network_mode: host
    container_name: collector
    image: otel/opentelemetry-collector-contrib:0.85.0
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
  jaeger:
    network_mode: host
    container_name: jaeger
    image: jaegertracing/all-in-one:1.49
    command: --collector.otlp.grpc.host-port 0.0.0.0:4310 --collector.otlp.http.host-port 0.0.0.0:4311
volumes:
  prometheus-data:
