global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: router
    static_configs:
      - targets: ["host.docker.internal:9999"]
  - job_name: router_metrics
    static_configs:
      - targets: ["0.0.0.0:9464"]
