global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: router
    static_configs:
      - targets: ["router:9090"]
  - job_name: router_metrics
    static_configs:
      - targets: ["collector:9464"]
