{
 "title": "Sample Router Dashboard for Prometheus",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "subgraphs",
    "label": "Subgraphs",
    "query": {
     "query": "label_values(apollo_router_http_requests_total{subgraph=~\".+\"}, subgraph)"
    }
   },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overall GraphQL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Rate by Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum by (operation_name) (rate(apollo_router_http_requests_total{has_errors=\"false\",subgraph=\"\"}[$__rate_interval]) or rate(apollo_router_http_requests_total{subgraph=\"\"}[$__rate_interval]) * 0)\n/ ignoring(has_errors) group_right(operation_name)\n  sum by (operation_name) (rate(apollo_router_http_requests_total{subgraph=\"\"}[$__rate_interval]))",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  {
   "title": "Requests per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_http_request_duration_seconds_count{subgraph=\"\"}[$__rate_interval]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(rate({__name__=\"apollo_router_http_request_duration_seconds_count\", error=~\".+\", subgraph=\"\"}[$__rate_interval]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(rate({__name__=\"apollo_router_http_request_duration_seconds_count\", error=\"\", subgraph=\"\"}[$__rate_interval]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Overall Response Times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(apollo_router_http_request_duration_seconds_bucket{subgraph=\"\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_http_request_duration_seconds_bucket{subgraph=\"\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(apollo_router_http_request_duration_seconds_bucket{subgraph=\"\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(apollo_router_http_request_duration_seconds_bucket{subgraph=\"\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Erroring Operations",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by(operation_name) (increase(apollo_router_http_requests_total{has_errors=\"true\"}[$__rate_interval])) != 0",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  { "title": "Router Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "README",
   "type": "text",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 20 },
   "options": {
    "content": "## Router Metrics\n\nThis section should ideally also include information about your Router pod(s), such as CPU, Memory, and otherwise. \n\nFor this example, we're relying on only fields that are configurable, however it may be worth considering adding in tools like cAdvisor or Node Exporter."
   }
  },
  {
   "title": "Lifecycle p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, span) (rate(apollo_router_span_bucket{subgraph=\"\"}[$__rate_interval])))",
     "legendFormat": "{{span}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, span, subgraph) (rate(apollo_router_span_bucket{subgraph=~\".+\"}[$__rate_interval])))",
     "legendFormat": "{{span}} - {{subgraph}}"
    }
   ]
  },
  {
   "title": "Router Cache Metrics",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "sum by(kind, storage) (rate(apollo_router_cache_hit_count_total[$__rate_interval]))",
     "legendFormat": "{{kind}} - {{storage}} - Hit"
    },
    {
     "expr": "sum by(kind, storage) (rate(apollo_router_cache_miss_count_total[$__rate_interval]))",
     "legendFormat": "{{kind}} - {{storage}} - Miss"
    }
   ]
  },
  { "title": "Subgraph $subgraphs Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }, "repeat": "subgraphs" },
  {
   "title": "Throughput/RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_http_requests_total{subgraph=\"$subgraphs\", status=~\".+\"}[$__rate_interval]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(rate(apollo_router_http_requests_total{subgraph=\"$subgraphs\", error=\"\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(rate(apollo_router_http_requests_total{subgraph=\"$subgraphs\", error=~\".+\"}[$__rate_interval]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Subgraph ($subgraphs) Response Times ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(apollo_router_http_request_duration_seconds_bucket{subgraph=\"$subgraphs\"}[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_http_request_duration_seconds_bucket{subgraph=\"$subgraphs\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(apollo_router_http_request_duration_seconds_bucket{subgraph=\"$subgraphs\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(apollo_router_http_request_duration_seconds_bucket{subgraph=\"$subgraphs\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}