{
 "title": "Sample Router v2 Dashboard for Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "subgraphs",
    "label": "Subgraphs",
    "query": {
     "query": "label_values(apollo_router_http_requests_total{subgraph=~\".+\"}, subgraph)"
    }
   },
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overall GraphQL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Rate by Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "  sum by (graphql_operation_name) (rate(http_server_request_duration_seconds_count{http_response_status_code=\"200\"}[$__rate_interval]) or rate(http_server_request_duration_seconds_count[$__rate_interval]) * 0)\n/ ignoring(http_response_status_code) group_right(graphql_operation_name)\n  sum by (graphql_operation_name) (rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  {
   "title": "Requests per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "Total Requests"
    },
    {
     "expr": "sum(rate({__name__=\"http_server_request_duration_seconds_count\", http_response_status_code!=\"200\"}[$__rate_interval]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(rate({__name__=\"http_server_request_duration_seconds_count\", http_response_status_code=\"200\"}[$__rate_interval]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Overall Response Times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Erroring Operations Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(graphql_operation_name) (increase(http_server_request_duration_seconds_count{http_response_status_code!=\"200\"}[$__range]))",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  {
   "title": "Supergraph requests duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_sum[$__rate_interval])) / sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "Request duration"
    }
   ]
  },
  { "title": "Subgraph $subgraphs Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }, "repeat": "subgraphs" },
  {
   "title": "Success Rate (subgraph)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_count{http_response_status_code=\"200\"}[$__rate_interval]) or rate(http_client_request_duration_seconds_count[$__rate_interval]) * 0)\n/ ignoring(http_response_status_code)\n  sum(rate(http_client_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "{{operation_name}}"
    }
   ]
  },
  {
   "title": "Subgraph requests duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_client_request_duration_seconds_sum[$__rate_interval]))  by(subgraph_name) / sum(rate(http_client_request_duration_seconds_count[$__rate_interval])) by(subgraph_name)",
     "legendFormat": "{{subgraph_name}}"
    }
   ]
  },
  {
   "title": "Subgraph cache hit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "entries" } },
   "targets": [
    {
     "expr": "sum by(subgraph_name, graphql_type_name) (rate(apollo_router_response_cache_total{cache_hit=\"true\"}[$__rate_interval]))",
     "legendFormat": "Cache hit {{subgraph_name}} - {{graphql_type_name}}"
    }
   ]
  },
  {
   "title": "Subgraph cache miss",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "entries" } },
   "targets": [
    {
     "expr": "sum by(subgraph_name, graphql_type_name) (rate(apollo_router_response_cache_total{cache_hit=\"false\"}[$__rate_interval]))",
     "legendFormat": "Cache miss {{subgraph_name}} - {{graphql_type_name}}"
    }
   ]
  },
  {
   "title": "Throughput/RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(subgraph_name) (rate(http_client_request_duration_seconds_count{response_cache_status=~\"miss|partial_hit\"}[$__rate_interval]))",
     "legendFormat": "Subgraph {{subgraph_name}}"
    }
   ]
  },
  {
   "title": "Subgraph entity fetch per req",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "entities" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_operations_response_cache_fetch_entity_sum[$__rate_interval]))  by(subgraph_name, graphql_type) / sum(rate(apollo_router_operations_response_cache_fetch_entity_count[$__rate_interval])) by(subgraph_name, graphql_type)",
     "legendFormat": "{{subgraph_name}} - {{graphql_type}}"
    }
   ]
  },
  { "title": "Router response cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Entities per subgraph fetch",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "entities" } },
   "targets": [
    {
     "expr": "ceil(sum(rate(apollo_router_operations_response_cache_fetch_entity_sum[$__rate_interval])) by(subgraph_name) / sum(rate(apollo_router_operations_response_cache_fetch_entity_count[$__rate_interval])) by(subgraph_name))",
     "legendFormat": "{{subgraph_name}}"
    }
   ]
  },
  {
   "title": "Cache storage fetch duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_operations_response_cache_fetch_seconds_sum[$__rate_interval])) / sum(rate(apollo_router_operations_response_cache_fetch_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache fetch errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_operations_response_cache_fetch_error_total[$__rate_interval])) by(subgraph_name, code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache storage insert duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_operations_response_cache_insert_seconds_sum[$__rate_interval])) / sum(rate(apollo_router_operations_response_cache_insert_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache storage reconnection",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_operations_response_cache_reconnection_total[$__rate_interval])) by(subgraph_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache insert errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_operations_response_cache_insert_error_total[$__rate_interval])) by(subgraph_name, code)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Invalidation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 75 } },
  {
   "title": "Invalidation duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_operations_response_cache_invalidation_duration_seconds_sum[$__rate_interval])) / sum(rate(apollo_router_operations_response_cache_invalidation_duration_seconds_count[$__rate_interval])) ",
     "legendFormat": "{{subgraph_name}}"
    }
   ]
  },
  {
   "title": "Invalidation rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_operations_response_cache_invalidation_event_total[$__rate_interval]))",
     "legendFormat": "{{subgraph_name}}"
    }
   ]
  },
  {
   "title": "Invalidation errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "errors" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_operations_response_cache_invalidation_error_total[$__rate_interval])) by(code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Invalidated entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "entries" } },
   "targets": [
    {
     "expr": "sum(rate(apollo_router_operations_response_cache_invalidation_entry_total[$__rate_interval])) by(subgraph_name, cache_tag, graphql_type)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}