receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  hostmetrics:
    collection_interval: 10s
    scrapers:
      paging:
        metrics:
          system.paging.utilization:
            enabled: true
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          system.cpu.physical.count:
            enabled: true
          system.cpu.logical.count:
            enabled: true
          system.cpu.frequency:
            enabled: true
      disk:
      filesystem:
        metrics:
          system.filesystem.utilization:
            enabled: true
      load:
      memory:
      network:
      processes:
  # The prometheus receiver scrapes metrics needed for the OpenTelemetry Collector Dashboard.
  prometheus/receiver:
    config:
      scrape_configs:
        - job_name: 'otelcol'
          scrape_interval: 10s
          static_configs:
            - targets: [ 'localhost:8888' ]

  docker_stats: # Note: doesn't work on MAC. Also, if you are using the collector image, you may need to configure additional permissions for the collector to have access to the Docker socket.  https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/11791
    endpoint: unix:///var/run/docker.sock # (default)
    metrics:
      container.network.io.usage.rx_packets:
        enabled: true
      container.network.io.usage.tx_packets:
        enabled: true
      container.cpu.usage.system:
        enabled: true
      container.memory.rss:
        enabled: true
      container.blockio.io_serviced_recursive:
        enabled: true
      container.uptime:
        enabled: true
      container.memory.hierarchical_memory_limit:
        enabled: true

processors:
  # The batch processor batches telemetry data into larger payloads.
  # It is necessary for the Datadog traces exporter to work optimally,
  # and is recommended for any production pipeline.
  batch:
    # Datadog APM Intake limit is 3.2MB. Let's make sure the batches do not
    # go over that.
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s

  # See more about sampling concepts here: https://opentelemetry.io/docs/concepts/sampling/
  # Tail sampling for intelligent sampling decisions. It requires all spans for a given trace to be sent to the same collector. 
  # If this is not the case, you can implement special load balencing via an oltp enpoint https://opentelemetry.io/docs/collector/deployment/gateway/ 
  # or fallback to the probablistic_sampler
  tail_sampling: # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/tailsamplingprocessor#readme
    decision_wait: 30s
    num_traces: 50000
    policies:
      # Always Sample GraphQL errors
      - name: graphql_errors
        type: boolean_attribute
        boolean_attribute:
          key: graphql.errors
          value: true
      # Always sample errors
      - name: errors
        type: status_code
        status_code:
          status_codes: [ERROR]
      # Always sample slow requests
      - name: slow_requests
        type: latency
        latency:
          threshold_ms: 1000
      # Random sampling for everything else
      - name: random_sampling
        type: probabilistic
        probabilistic:
          sampling_percentage: 10

    # # Probabilistic sampling for consistent sampling across incomplete traces
    # probabilistic_sampler:
    #   sampling_percentage: 100 # Keep all traces that make it to collector

  # doesnt work with mac
  #  resourcedetection/docker:
  #    detectors: [env, docker]
  #    timeout: 2s
  #    override: false

  resourcedetection:
    # bare metal
    detectors: [ env, system ]
    system:
      resource_attributes:
        os.description:
          enabled: true
        host.arch:
          enabled: true
        host.cpu.vendor.id:
          enabled: true
        host.cpu.family:
          enabled: true
        host.cpu.model.id:
          enabled: true
        host.cpu.model.name:
          enabled: true
        host.cpu.stepping:
          enabled: true
        host.cpu.cache.l2.size:
          enabled: true
#    # GCP
#    detectors: [ env, gcp, system ]
#    # AWS
#    detectors: [ env, ecs, ec2, system ]
#    # Azure
#    detectors: [ env, azure, system ]
#    timeout: 2s
#    override: false

#  resourcedetection/docker:
#    detectors: [ env, docker ]
#    timeout: 2s
#    override: false


# Read more about exporters here:
# https://opentelemetry.io/docs/collector/configuration/#connectors
connectors:
  # The Datadog connector is necessary for APM Trace metrics.
  datadog/connector:

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: jaeger:4310
    tls:
      insecure: true
  datadog/exporter: #https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/datadogexporter and https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/examples/collector.yaml
    traces:
      trace_buffer: 500
    metrics:
      # Add all resource attributes as tags for metrics https://docs.datadoghq.com/opentelemetry/mapping/semantic_mapping/?tab=datadogexporter#metrics-attribute-mapping
      resource_attributes_as_tags: true
      histograms: # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/examples/collector.yaml#L277
        mode: distributions
        send_aggregation_metrics: true
    api:
      key: ${env:DD_API_KEY} # Set your Datadog API key as an environment variable
      #site: "datadoghq.com" # Use "datadoghq.eu" if you're in the EU region
extensions:
  health_check:
  zpages:
#  datadog:  # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/extension/datadogextension/README.md
#    api:
#      key: ${env:DD_API_KEY}
#      site: "datadoghq.com"
#    http:
#      endpoint: "localhost:9875"
#      path: "/metadata"

service:
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus: # view at http://localhost:8888/metrics
                host: 0.0.0.0
                port: 8888
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, batch]
      exporters: [otlp, datadog/connector]
    traces/sampling: # https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/datadogexporter/examples/collector.yaml#L517
      receivers: [datadog/connector]
      processors: [tail_sampling]
      exporters: [datadog/exporter]
    metrics:
      receivers: [hostmetrics, otlp, prometheus/receiver, datadog/connector, docker_stats]
      processors: [resourcedetection, batch]
      exporters: [datadog/exporter]

