receivers:
  otlp:
    protocols:
      grpc:
      http:
  otlp/spanmetrics:
    protocols:
      grpc:
        endpoint: 0.0.0.0:12346

processors:
  batch:
  spanmetrics:
    metrics_exporter: prometheus

exporters:
  logging:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9464"
  otlp:
    endpoint: jaeger:4310
    tls:
      insecure: true
extensions:
  health_check:
  zpages:

service:
  extensions: [health_check, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, spanmetrics]
      exporters: [otlp]
    metrics:
      receivers: [otlp/spanmetrics, otlp]
      processors: [batch]
      exporters: [prometheus]
